/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthDialog: typeof import('./src/components/AuthDialog.vue')['default']
    BaseAlert: typeof import('./src/components/ui/BaseAlert.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/ui/BaseCard.vue')['default']
    BaseDialog: typeof import('./src/components/ui/BaseDialog.vue')['default']
    BaseInput: typeof import('./src/components/ui/BaseInput.vue')['default']
    BasePopconfirm: typeof import('./src/components/ui/BasePopconfirm.vue')['default']
    BaseRadioGroup: typeof import('./src/components/ui/BaseRadioGroup.vue')['default']
    BaseSelect: typeof import('./src/components/ui/BaseSelect.vue')['default']
    BaseSwitch: typeof import('./src/components/ui/BaseSwitch.vue')['default']
    BaseTabPane: typeof import('./src/components/ui/BaseTabPane.vue')['default']
    BaseTabs: typeof import('./src/components/ui/BaseTabs.vue')['default']
    BaseToast: typeof import('./src/components/ui/BaseToast.vue')['default']
    BaseTooltip: typeof import('./src/components/ui/BaseTooltip.vue')['default']
    SessionPanel: typeof import('./src/components/SessionPanel.vue')['default']
  }
}
